### ISSUE TITLE
ImportError: cannot import name 'validate_monitoring_pods_are_respinned_and_running_state' from 'ocs_ci.ocs.monitoring'

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#626]
This module `tests/e2e/test_running_cluster_monitoring_with_persistent_storage.py`
is going to be deleted in pr #479 but for quick fix we need to delete this file now to get this fixed as another PR got merged before #479 and causing this issue.

**Comment by zmc** [comment]
Just for posterity, the breakage was caused by https://github.com/red-hat-storage/ocs-ci/pull/506
