### PR TITLE
Fix arguments issue in bucket factory fixture

### LINKED ISSUE #2614: TypeError: bucket_factory_fixture() got an unexpected keyword argument 'rgw_obj_session'
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/2473/testReport/
```
request = <SubRequest 'bucket_factory_session' for <Function test_fill_bucket>>
mcg_obj_session = <ocs_ci.ocs.resources.mcg.MCG object at 0x7f810836feb8>

    @pytest.fixture(scope='session')
    def bucket_factory_session(request, mcg_obj_session):
        """
        Returns a session-scoped MCG bucket factory
        """
>       return bucket_factory_fixture(request, mcg_obj_session, rgw_obj_session=None)
E       TypeError: bucket_factory_fixture() got an unexpected keyword argument 'rgw_obj_session'

tests/conftest.py:1773: TypeError
```

### PR DESCRIPTION
**Pull request by ebenahar**
Fixed #2614

Signed-off-by: Elad Ben Aharon <ebenahar@redhat.com>

### CODE REVIEW

**Comment by ebenahar** [comment]
Upgade execution with pre and post upgrade passed the pre upgrade tests phase, in which the failure was seen before.
Before this fix:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/2473/testReport/
After this fix:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/10479/consoleFull

It later failed as 1 mon failed to be upgraded, but that's an issue that will be fixed with https://github.com/red-hat-storage/ocs-ci/pull/2570 and was reported in https://bugzilla.redhat.com/show_bug.cgi?id=1856254


Marking as verified
