### PR TITLE
set iam_endpoint to None on Azure

### LINKED ISSUE #14964: [Bug]: Azure deployment is failing with missing IAM endpint
### Description

```
026-04-23 15:39:12  get_noobaa = {'apiVersion': 'v1', 'items': [{'apiVersion': 'noobaa.io/v1alpha1', 'kind': 'NooBaa', 'metadata': {'annotations': {'Mu...ging': {}, 'bucketNotifications': {'enabled': False}, ...}, ...}], 'kind': 'List', 'metadata': {'resourceVersion': ''}}
2026-04-23 15:39:12  
2026-04-23 15:39:12      def __init__(self, *args, **kwargs):
2026-04-23 15:39:12          """
2026-04-23 15:39:12          Constructor for the MCG class
2026-04-23 15:39:12          """
2026-04-23 15:39:12          with config.RunWithProviderConfigContextIfAvailable():
2026-04-23 15:39:12              self.namespace = config.ENV_DATA["cluster_namespace"]
2026-04-23 15:39:12              self.operator_pod = Pod(
2026-04-23 15:39:12                  **get_pods_having_label(
2026-04-23 15:39:12                      constants.NOOBAA_OPERATOR_POD_LABEL, self.namespace
2026-04-23 15:39:12                  )[0]
2026-04-23 15:39:12              )
2026-04-23 15:39:12              self.core_pod = Pod(
2026-04-23 15:39:12                  **get_pods_having_label(
2026-04-23 15:39:12                      constants.NOOBAA_CORE_POD_LABEL, self.namespace
2026-04-23 15:39:12                  )[0]
2026-04-23 15:39:12              )
2026-04-23 15:39:12              wait_for_resource_state(
2026-04-23 15:39:12                  resource=self.operator_pod, state=constants.STATUS_RUNNING, timeout=300
2026-04-23 15:39:12              )
2026-04-23 15:39:12      
2026-04-23 15:39:12              # Determine which CLI to use based on version
2026-04-23 15:39:12              self.cli_path, self.command_prefix = get_noobaa_cli_config()
2026-04-23 15:39:12              ocs_version = version.get_semantic_ocs_version_from_config()
2026-04-23 15:39:12      
2026-04-23 15:39:12              # Initialize ODFCliRunner for OCS >= 4.20
2026-04-23 15:39:12              self.odf_cli_runner = None
2026-04-23 15:39:12              if ocs_version >= version.VERSION_4_20:
2026-04-23 15:39:12                  from ocs_ci.helpers.odf_cli import ODFCliRunner
2026-04-23 15:39:12      
2026-04-23 15:39:12                  self.odf_cli_runner = ODFCliRunner()
2026-04-23 15:39:12      
2026-04-23 15:39:12              if (
2026-04-23 15:39:12                  not os.path.isfile(self.cli_path)
2026-04-23 15:39:12                  or self.get_mcg_cli_version().minor != ocs_version.minor
2026-04-23 15:39:12              ):
2026-04-23 15:39:12                  logger.info(
2026-04-23 15:39:12                      "The expected NooBaa CLI binary could not be found,"
2026-04-23 15:39:12                      " downloading the expected version"
2026-04-23 15:39:12                  )
2026-04-23 15:39:12                  if ocs_version >= version.VERSION_4_20:
2026-04-23 15:39:12                      retrieve_cli_binary(cli_type="odf")
2026-04-23 15:39:12                  else:
2026-04-23 15:39:12                      retrieve_cli_binary(cli_type="mcg")
2026-04-23 15:39:12      
2026-04-23 15:39:12              """
2026-04-23 15:39:12              The certificate will be copied on each mcg_obj instantiation since
2026-04-23 15:39:12              the process is so light and quick, that the time required for the redundant
2026-04-23 15:39:12              copy is neglible in comparison to the time a hash comparison will take.
2026-04-23 15:39:12              """
2026-04-23 15:39:12              retrieve_default_ingress_crt()
2026-04-23 15:39:12      
2026-04-23 15:39:12              get_noobaa = OCP(kind="noobaa", namespace=self.namespace).get()
2026-04-23 15:39:12      
2026-04-23 15:39:12              self.s3_endpoint = (
2026-04-23 15:39:12                  get_noobaa.get("items")[0]
2026-04-23 15:39:12                  .get("status")
2026-04-23 15:39:12                  .get("services")
2026-04-23 15:39:12                  .get("serviceS3")
2026-04-23 15:39:12                  .get("externalDNS")[0]
2026-04-23 15:39:12              )
2026-04-23 15:39:12              self.s3_internal_endpoint = self.determine_s3_endpoint()
2026-04-23 15:39:12              self.sts_endpoint = (
2026-04-23 15:39:12                  get_noobaa.get("items")[0]
2026-04-23 15:39:12                  .get("status")
2026-04-23 15:39:12                  .get("services")
2026-04-23 15:39:12                  .get("serviceSts")
2026-04-23 15:39:12                  .get("externalDNS")[0]
2026-04-23 15:39:12              )
2026-04-23 15:39:12              self.sts_internal_endpoint = (
2026-04-23 15:39:12                  get_noobaa.get("items")[0]
2026-04-23 15:39:12                  .get("status")
2026-04-23 15:39:12                  .get("services")
2026-04-23 15:39:12                  .get("serviceSts")
2026-04-23 15:39:12                  .get("internalDNS")[0]
2026-04-23 15:39:12              )
2026-04-23 15:39:12              self.mgmt_endpoint = (
2026-04-23 15:39:12                  get_noobaa.get("items")[0]
2026-04-23 15:39:12                  .get("status")
2026-04-23 15:39:12                  .get("services")
2026-04-23 15:39:12                  .get("serviceMgmt")
2026-04-23 15:39:12                  .get("externalDNS")[0]
2026-04-23 15:39:12              ) + "/rpc"
2026-04-23 15:39:12              self.iam_endpoint = (
2026-04-23 15:39:12                  get_noobaa.get("items")[0]
2026-04-23 15:39:12                  .get("status")
2026-04-23 15:39:12                  .get("services")
2026-04-23 15:39:12                  .get("serviceIam")
2026-04-23 15:39:12  >               .get("externalDNS")[0]
2026-04-23 15:39:12              )
2026-04-23 15:39:12  E           AttributeError: 'NoneType' object has no attribute 'get'
2026-04-23 15:39:12  
2026-04-23 15:39:12  ocs_ci/ocs/resources/mcg.py:165: AttributeError
```

job: https://url.corp.redhat.com/b6c285c

regressed by https://github.com/red-hat-storage/ocs-ci/pull/14774

### PR DESCRIPTION
**Pull request by vavuthu**
Fixes: #14964

Signed-off-by: vavuthu [vavuthu@redhat.com](mailto:vavuthu@redhat.com)

### CODE REVIEW

**Comment by vavuthu** [comment]
verifed: https://url.corp.redhat.com/6e2aa1c

```
2026-04-23 19:57:56  10:27:56 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get noobaa -n openshift-storage -o yaml
2026-04-23 19:57:56  10:27:56 - MainThread - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n openshift-storage get noobaa -n openshift-storage -o yaml
2026-04-23 19:57:56  10:27:56 - MainThread - ocs_ci.ocs.resources.mcg - INFO  - serviceIam not found in NooBaa services - IAM endpoint will not be available
```

**Review by petr-balogh — APPROVED** [review]

**Review by dahorak — APPROVED** [review]
