### ISSUE TITLE
tests.helpers.create_resource Attribute error when wait=True

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#451]
When calling `tests.helpers.create_resource` with parameter `wait=True` then there is an Attribute error:

```
    def wait_for_resource_state(resource, state):
        """
        Wait for a resource to get to a given status
    
        Args:
            resource (OCS obj): The resource object
            state (str): The status to wait for
    
        Returns:
            bool: True if resource reached the desired state, False otherwise
        """
        try:
>           resource.ocp.wait_for_resource(
                condition=state, resource_name=resource.name
            )
E           AttributeError: 'str' object has no attribute 'ocp'

tests/helpers.py:82: AttributeError
```

**Comment by RazTamir** [comment]
@shreekarSS , I think this regression was introduced with https://github.com/red-hat-storage/ocs-ci/pull/357

**Comment by vasukulkarni** [comment]
closing stale issue.
