### PR TITLE
add capacity 

### PR DESCRIPTION
**Pull request by annagitel**
Signed-off-by: annagitel <asandler@redhat.com>

### CODE REVIEW

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 1]
```diff
@@ -294,3 +295,41 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
                 item for item in crush_rule['steps'] if item.get('type') == 'zone'
             ], f"{crush_rule['rule_name']} is not with type as zone"
         log.info("Verified - pool crush rule is with type: zone")
+
+
+def add_capacity(capacity):
+    """
+   Add storage capacity to the cluster
```
Comment (ebenahar) [inline ocs_ci/ocs/resources/storage_cluster.py]: add empty lines between the docstring sections

File: tests/manage/z_cluster/cluster_expansion/test_add_capacity.py [hunk 2]
```diff
@@ -1,51 +1,33 @@
...
+from ocs_ci.framework.testlib import ignore_leftovers, ManageTest
+from ocs_ci.framework.pytest_customization.marks import polarion_id, tier3
+from ocs_ci.ocs.resources import storage_cluster
+
 logger = logging.getLogger(__name__)
 
 
 @ignore_leftovers
-@tier1
+@tier3
```
Comment (ebenahar) [inline tests/manage/z_cluster/cluster_expansion/test_add_capacity.py]: should be tier1

Comment (annagitel) [reply tests/manage/z_cluster/cluster_expansion/test_add_capacity.py]: in row 5 too?

Comment (annagitel) [reply tests/manage/z_cluster/cluster_expansion/test_add_capacity.py]: @ebenahar in row 5 too?

Comment (annagitel) [reply tests/manage/z_cluster/cluster_expansion/test_add_capacity.py]: @ebenahar in row 5 too?

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 3]
```diff
@@ -294,3 +295,41 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+   Args:
+        capacity(int): Size of the storage to add as number of deviceSets
+   Returns:
+        boolean : Returns True if all OSDs are in Running state
+   """
+    ocp = OCP(namespace=defaults.ROOK_CLUSTER_NAMESPACE, kind=constants.STORAGECLUSTER)
+    sc = ocp.get()
+    device_set_count = sc.get('items')[0].get('spec').get('storageDeviceSets')[0].get('count')
+    capacity_to_add = device_set_count + capacity
```
Comment (hnallurv) [inline ocs_ci/ocs/resources/storage_cluster.py]: As mentioned in earlier comments in old PRs, the formula to derive the storageDeviceSets->count to add additional capacity is as follows:
storageDeviceSets->count = (capacity requested / osd capacity ) + existing count storageDeviceSets

I don't see that here. 

So, If i pass 512 GiB as int (i.e., just 512), then from your code, capacity_to_add  will have 512 + device_set_count. When this is 'patched', it would result in 512+device_set_count number of osds getting added to the system. Isn't it?

Can you please check and change the code accordingly?

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 4]
```diff
@@ -294,3 +295,41 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+
+    # adding the storage capacity to the cluster
+    params = f"""[{{"op": "replace", "path": "/spec/storageDeviceSets/0/count", "value":{capacity_to_add}}}]"""
+    ocp.patch(
+        resource_name=sc['items'][0]['metadata']['name'],
+        params=params,
+        format_type='json'
+    )
+    pod = Pod()
+    pod.ocp.wait_for_resource(timeout=180, condition=constants.STATUS_RUNNING,
```
Comment (hnallurv) [inline ocs_ci/ocs/resources/storage_cluster.py]: may be a good idea to increase the timeout to 300 to be on safer side.

File: ocs_ci/ocs/resources/storage_cluster.py (hunk 3 above)
Comment (annagitel) [reply ocs_ci/ocs/resources/storage_cluster.py]: the code was changed that the function will get number of deviceSets to add instead of capacity in GB/TB

File: ocs_ci/ocs/resources/storage_cluster.py (hunk 4 above)
Comment (annagitel) [reply ocs_ci/ocs/resources/storage_cluster.py]: will do

File: tests/manage/z_cluster/cluster_expansion/test_add_capacity.py [hunk 5]
```diff
@@ -1,51 +1,33 @@
...
     )
-    def test_add_capacity(self, node_multiplier, capacity):
+    def test_add_capacity(self, capacity):
         """
         Test to add variable capacity to the OSD cluster while IOs running
 
         Args:
-        node_multiplier: the number of OSD to add per worker node
-        capacity: the storage capacity of each OSD
+           capacity (int):the storage capacity to add as deviceSet number
```
[the remark this answers is not in the document]
Comment (annagitel) [reply tests/manage/z_cluster/cluster_expansion/test_add_capacity.py]: the code was changes so the function will get a number of device sets to ad  and not an capacity value

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 6]
```diff
@@ -294,3 +294,45 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+    capacity_to_add = device_set_count + capacity
+
+    # adding the storage capacity to the cluster
+    params = f"""[{{"op": "replace", "path": "/spec/storageDeviceSets/0/count", "value":{capacity_to_add}}}]"""
+    ocp.patch(
+        resource_name=sc['items'][0]['metadata']['name'],
+        params=params,
+        format_type='json'
+    )
+    pod = ocp.OCP(
```
[the remark this answers is not in the document]
Comment (shreekarSS) [reply ocs_ci/ocs/resources/storage_cluster.py]: >       pod = ocp.OCP(
            kind=constants.POD, namespace=config.ENV_DATA['cluster_namespace']
        )
E       AttributeError: 'OCP' object has no attribute 'OCP'

File: ocs_ci/ocs/resources/storage_cluster.py (hunk 3 above)
Comment (hnallurv) [reply ocs_ci/ocs/resources/storage_cluster.py]: We would like to keep add_capacity as generic as possible. It should work with both 4.2 and 4.3. From user point of view, the add_capacity needs to accept the capacity as a parameter. User does not have to know about osds and deviceSetcount and calculate them before calling add_capacity function. So, I would like this function to accept 'capacity to add' as parameter to it and use the formula internally to know the actual count of storagedevicesets to be 'patched' to meet the 'capacity to add'.
Please contact me or Shreekara if you need any clarification on this. Thanks!

File: tests/manage/z_cluster/cluster_expansion/test_add_capacity.py [hunk 7]
```diff
@@ -17,35 +13,10 @@ class TestAddCapacity(ManageTest):
...
-            machine_utils.add_storage_capacity(storagecluster_name=storage_cluster, capacity=capacity)
-            pod_obj = ocp.OCP(kind=constants.POD, namespace=defaults.ROOK_CLUSTER_NAMESPACE)
-            assert pod_obj.wait_for_resource(
-                condition=constants.STATUS_RUNNING, selector=constants.OSD_APP_LABEL,
-                resource_count=worker_nodes * node_multiplier, timeout=600
-            ), "OSD pods failed to reach RUNNING state"
-        else:
-            pytest.skip("UPI not yet supported")
-        # ToDo run IOs
+        osd_size = storage_cluster.get_osd_size()
```
Comment (hnallurv) [inline tests/manage/z_cluster/cluster_expansion/test_add_capacity.py]: this works for OCS 4.3 only as expansion there is done in the increments of size of the osd with which cluster is deployed initially.

For OCS 4.2, you need to pass the capacity in the multiples of 2TiB.

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 8]
```diff
@@ -288,9 +288,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+        crush_rules = [rule for rule in crush_dump['rules']
+                       if rule['rule_name'] in pool_names]
         for crush_rule in crush_rules:
             assert [
                 item for item in crush_rule['steps'] if item.get('type') == 'zone'
             ], f"{crush_rule['rule_name']} is not with type as zone"
         log.info("Verified - pool crush rule is with type: zone")
+
+
+def add_capacity(osd_size_capacity_requested):
```
Comment (hnallurv) [inline ocs_ci/ocs/resources/storage_cluster.py]: change osd_size_capacity_requested  to capacity_requested

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 9]
```diff
@@ -288,9 +288,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+    "Patch" this count to get the required capacity to add.
+    To do so, we use following formula:
+    storageDeviceSets->count = (capacity reqested / osd capacity ) + existing count storageDeviceSets
+    """
+
+    sc = get_storage_cluster()
+    old_storage_devices_sets_count = get_deviceset_count()
+    osd_size_existing = get_osd_size()
+    new_storage_devices_sets_count = int(
+        (osd_size_capacity_requested /
```
Comment (ebenahar) [inline ocs_ci/ocs/resources/storage_cluster.py]: break lines with parentheses

**Comment by shreekarSS** [comment]
tested on AWS and vmware and found it working
****
   osd: 9 osds: 9 up (since 36s), 9 in (since 36s)
 
  data:
    pools:   3 pools, 136 pgs
    objects: 357 objects, 589 MiB
    usage:   9.9 GiB used, 36 TiB / 36 TiB avail
    pgs:     136 active+clean

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 10]
```diff
@@ -292,9 +292,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
             constants.METADATA_POOL, constants.DEFAULT_BLOCKPOOL,
             constants.DATA_POOL
         ]
-        crush_rules = [rule for rule in crush_dump['rules'] if rule['rule_name'] in pool_names]
+        crush_rules = [rule for rule in crush_dump['rules']
```
Comment (RazTamir) [inline ocs_ci/ocs/resources/storage_cluster.py]: fix parenthesis:
crush_rules = [
    ...
]

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 11]
```diff
@@ -292,9 +292,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
         for crush_rule in crush_rules:
             assert [
                 item for item in crush_rule['steps'] if item.get('type') == 'zone'
             ], f"{crush_rule['rule_name']} is not with type as zone"
         log.info("Verified - pool crush rule is with type: zone")
+
+
+def add_capacity(osd_size_capacity_requested):
+    """
+    Add storage capacity to the cluster
```
Comment (RazTamir) [inline ocs_ci/ocs/resources/storage_cluster.py]: add new empty line

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 12]
```diff
@@ -292,9 +292,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+    Args:
+        osd_size_capacity_requested(int): Requested osd size capacity
```
Comment (RazTamir) [inline ocs_ci/ocs/resources/storage_cluster.py]: add space between the parameter name and the (type)

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 13]
```diff
@@ -292,9 +292,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+
+    Returns:
+        boolean : Returns True if all OSDs are in Running state
```
Comment (RazTamir) [inline ocs_ci/ocs/resources/storage_cluster.py]: bool instead of boolean

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 14]
```diff
@@ -292,9 +292,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+    """
+
+    """
+    Note:
```
Comment (RazTamir) [inline ocs_ci/ocs/resources/storage_cluster.py]: move this entire note to the docstring above

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 15]
```diff
@@ -292,9 +292,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+    From this we need to arrive at storagedeviceSets -> count and then
+    "Patch" this count to get the required capacity to add.
+    To do so, we use following formula:
+    storageDeviceSets->count = (capacity reqested / osd capacity ) + existing count storageDeviceSets
+    """
+
+    sc = get_storage_cluster()
+    old_storage_devices_sets_count = get_deviceset_count()
+    osd_size_existing = get_osd_size()
+    new_storage_devices_sets_count = int((osd_size_capacity_requested / osd_size_existing)
```
Comment (RazTamir) [inline ocs_ci/ocs/resources/storage_cluster.py]: fix parenthesis

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 16]
```diff
@@ -292,9 +292,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+                                         + old_storage_devices_sets_count
+                                         )
+    # adding the storage capacity to the cluster
+    params = f"""
```
Comment (RazTamir) [inline ocs_ci/ocs/resources/storage_cluster.py]: fix alignment here

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 17]
```diff
@@ -292,9 +292,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+        format_type='json'
+    )
+    pod = OCP(
+        kind=constants.POD, namespace=config.ENV_DATA['cluster_namespace']
+    )
+    pod.wait_for_resource(
+        timeout=180,
+        condition=constants.STATUS_RUNNING,
+        selector='app=rook-ceph-osd',
+        resource_count=new_storage_devices_sets_count * 3)
```
Comment (RazTamir) [inline ocs_ci/ocs/resources/storage_cluster.py]: ) in new line

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 18]
```diff
@@ -292,9 +292,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+    return True
+
+
+def get_storage_cluster(namespace=defaults.ROOK_CLUSTER_NAMESPACE):
+    """
+   Get storage cluster name
```
Comment (RazTamir) [inline ocs_ci/ocs/resources/storage_cluster.py]: new empty line

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 19]
```diff
@@ -292,9 +292,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+def get_osd_size():
+    """
+    Get osd size from Storage cluster
+
+    Returns:
+        int: osd size
+    """
+    sc = get_storage_cluster()
+    return int(sc.get().get('items')[0].get('spec').get('storageDeviceSets')[0]. get(
+        'dataPVCTemplate').get('spec').get('resources').get('requests').get('storage')[:-2])
```
Comment (RazTamir) [inline ocs_ci/ocs/resources/storage_cluster.py]: fix parenthesis

File: ocs_ci/ocs/resources/storage_cluster.py [hunk 20]
```diff
@@ -292,9 +292,104 @@ def ocs_install_verification(timeout=600, skip_osd_distribution_check=False):
...
+def get_deviceset_count():
+    """
+    Get storageDeviceSets count  from storagecluster
+
+    Returns:
+        int: storageDeviceSets count
+    """
+    sc = get_storage_cluster()
+    return int(sc.get().get('items')[0].get('spec').get(
+        'storageDeviceSets')[0].get('count'))
```
Comment (RazTamir) [inline ocs_ci/ocs/resources/storage_cluster.py]: same

File: tests/manage/z_cluster/cluster_expansion/test_add_capacity.py [hunk 21]
```diff
@@ -17,35 +12,10 @@ class TestAddCapacity(ManageTest):
...
+        result = storage_cluster.add_capacity(osd_size)
+        assert result, logger.info("Test Failed, new pods failed reaching running state")
```
Comment (RazTamir) [inline tests/manage/z_cluster/cluster_expansion/test_add_capacity.py]: assert result, "<ERROR MESSAGE>"
no need for logger.info

Comment (PrasadDesala) [inline tests/manage/z_cluster/cluster_expansion/test_add_capacity.py]: Post successful addition of capacity it would be better to check for the ceph health state and confirm that it is Healthy (we will have to to wait till the rebalance completes if any).
through which,
1) we can confirm that there are no issues wrt ceph post addition of add-capacity
2) If the number of OSDs added are more, rebalance will take more time. So, there are high chances that the next running test might fail since ceph health status is not healthy.
Thoughts?

File: ocs_ci/ocs/resources/storage_cluster.py (hunk 10 above)
Comment (annagitel) [reply ocs_ci/ocs/resources/storage_cluster.py]: this func is not part of the PR

File: tests/manage/z_cluster/cluster_expansion/test_add_capacity.py (hunk 21 above)
Comment (hnallurv) [reply tests/manage/z_cluster/cluster_expansion/test_add_capacity.py]: Thanks Prasad. test_add_capacity.py will have more changes in coming days like entry and exit criteria verification. The main focus of this PR for now is to implement the core part of cluster expansion, the 'add_capacity' function. 

Shreekara/Anna, Request you to move the code "pod.ocp.wait_for_resource" out of the 'add_capacity' function. We need add_capacity function to just 'patch' and come out. Rest of the things like verification should be handled by the test script calling it. This way it will help both tier1 and tier4 tests to use this function w/o modifying. For tier4 we need to introduce the failures while rebuild or osd addition is going on. If we make add_capacity function to wait for the above to complete in it then it will be difficult for tier4 tests introduce the failure at the right time.
